services:
  web:
    build: .
    container_name: appposto-web
    ports:
      - "8081:8000"  # Porta externa 8081 mapeada para a interna 8000
    environment:
      - DATABASE_URL=postgresql+psycopg://appposto_db:123Delagoa4@db:65432/combustivel
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: appposto-db
    ports:
      - "65432:5432"
    environment:
      POSTGRES_USER: appposto_db
      POSTGRES_PASSWORD: 123Delagoa4
      POSTGRES_DB: combustivel

volumes:
  postgres_data:
