version: '3.9'

services:
  web:
    build: .
    container_name: appposto-web
    ports:
      - "8081:8000"  # Porta 8081 no host mapeada para 8000 no contêiner
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+psycopg://appposto_db:123Delagoa4@db:5432/combustivel
    depends_on:
      - db
    networks:
      - appposto-network

  db:
    image: postgres:15
    container_name: appposto-db
    environment:
      POSTGRES_USER: appposto_db
      POSTGRES_PASSWORD: 123Delagoa4
      POSTGRES_DB: combustivel
    ports:
      - "65432:5432"  # Porta 65432 no host mapeada para 5432 no contêiner
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appposto-network

volumes:
  postgres_data:

networks:
  appposto-network:
