"""Cria tabelas municipio e endereco

Revision ID: ae41d7ea282a
Revises: 
Create Date: 2024-12-23 09:32:19.004647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae41d7ea282a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipio',
    sa.Column('id_ibge', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('regiao', sa.String(), nullable=False),
    sa.Column('nome_regiao', sa.String(), nullable=False),
    sa.Column('data_inclusao', sa.DateTime(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_ibge')
    )
    op.create_index(op.f('ix_municipio_id_ibge'), 'municipio', ['id_ibge'], unique=False)
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('tipo', sa.Enum('PRINCIPAL', 'CORRESPONDENCIA', 'COBRANCA', name='tipoendereco'), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('data_inclusao', sa.DateTime(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id_ibge'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endereco_id'), 'endereco', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endereco_id'), table_name='endereco')
    op.drop_table('endereco')
    op.drop_index(op.f('ix_municipio_id_ibge'), table_name='municipio')
    op.drop_table('municipio')
    # ### end Alembic commands ###
